apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: go-api
    newName: ghcr.io/aliaksandr-budnikau/go-api
    newTag: v1.1.0