apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
  - name: go-api
    newName: ghcr.io/aliaksandr-budnikau/go-api:v1.0.0
    newTag: v1.0.0