apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: go-api-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/aliaksandr-budnikau/go-api-gitops.git
        revision: main
        directories:
          - path: apps/go-api/overlays/*
  template:
    metadata:
      name: 'go-api-{{path.basename}}'
      labels:
        app: go-api
        env: '{{path.basename}}'
    spec:
      project: go-api
      source:
        repoURL: https://github.com/aliaksandr-budnikau/go-api-gitops.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 30s