apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: go-api-prod
spec:
  project: go-api
  source:
    repoURL: https://github.com/aliaksandr-budnikau/go-api-gitops.git
    targetRevision: main
    path: apps/go-api/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true